[2025-07-26T09:28:14.810+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:28:14.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:28:14.816+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:28:14.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:28:17.375+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:28:17.161+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:28:17.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:28:17.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 3.037 seconds
[2025-07-26T09:28:48.163+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:28:48.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:28:48.169+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:28:48.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:28:49.028+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:28:48.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:28:49.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:28:49.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.913 seconds
[2025-07-26T09:29:19.635+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:29:19.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:29:19.642+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:29:19.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:29:20.224+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:29:20.166+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:29:20.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:29:20.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.676 seconds
[2025-07-26T09:29:51.028+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:29:51.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:29:51.043+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:29:51.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:29:51.915+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:29:51.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:29:51.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:29:51.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.959 seconds
[2025-07-26T09:30:22.356+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:30:22.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:30:22.361+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:30:22.360+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:30:22.890+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:30:22.873+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:30:22.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:30:22.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.599 seconds
[2025-07-26T09:30:53.501+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:30:53.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:30:53.510+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:30:53.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:30:54.211+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:30:54.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:30:54.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:30:54.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.832 seconds
[2025-07-26T09:31:24.781+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:31:24.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:31:24.785+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:31:24.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:31:25.554+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:31:25.532+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:31:25.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:31:25.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.863 seconds
[2025-07-26T09:31:56.181+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:31:56.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:31:56.189+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:31:56.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:31:56.912+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:31:56.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:31:56.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:31:56.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.800 seconds
[2025-07-26T09:32:27.439+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:32:27.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:32:27.450+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:32:27.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:32:28.066+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:32:28.052+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:32:28.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:32:28.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.709 seconds
[2025-07-26T09:32:58.202+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:32:58.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:32:58.207+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:32:58.207+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:32:59.247+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:32:59.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:32:59.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:32:59.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 1.234 seconds
[2025-07-26T09:33:29.619+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:33:29.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:33:29.625+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:33:29.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:33:30.277+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:33:30.262+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:33:30.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:33:30.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.723 seconds
[2025-07-26T09:34:00.808+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:34:00.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:34:00.831+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:34:00.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:34:01.647+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:34:01.633+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:34:01.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:34:01.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.925 seconds
[2025-07-26T09:34:32.141+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:34:32.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:34:32.146+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:34:32.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:34:32.923+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:34:32.765+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:34:32.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:34:33.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.982 seconds
[2025-07-26T09:35:03.530+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:35:03.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:35:03.537+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:35:03.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:35:04.028+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:35:04.014+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:35:04.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:35:04.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.545 seconds
[2025-07-26T09:35:34.483+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:35:34.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:35:34.489+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:35:34.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:35:35.112+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:35:35.095+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:35:35.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:35:35.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.691 seconds
[2025-07-26T09:36:05.316+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:36:05.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:36:05.322+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:36:05.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:36:05.912+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:36:05.898+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:36:05.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:36:05.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.655 seconds
[2025-07-26T09:36:36.304+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:36:36.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:36:36.310+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:36:36.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:36:36.868+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:36:36.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:36:36.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:36:36.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.618 seconds
[2025-07-26T09:37:07.085+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:37:07.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:37:07.092+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:37:07.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:37:07.894+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:37:07.878+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:37:07.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:37:07.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.888 seconds
[2025-07-26T09:37:38.504+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:37:38.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:37:38.530+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:37:38.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:37:39.022+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:37:39.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:37:39.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:37:39.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.609 seconds
[2025-07-26T09:38:09.485+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:38:09.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:38:09.493+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:38:09.492+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:38:10.098+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:38:10.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:38:10.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:38:10.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.663 seconds
[2025-07-26T09:38:40.972+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:38:41.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:38:41.007+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:38:41.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:38:41.526+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:38:41.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:38:41.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:38:41.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.596 seconds
[2025-07-26T09:39:12.005+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:39:12.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:39:12.013+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:39:12.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:39:12.656+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:39:12.644+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:39:12.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:39:12.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.723 seconds
[2025-07-26T09:39:43.022+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:39:43.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:39:43.063+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:39:43.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:39:43.641+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:39:43.579+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:39:43.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:39:43.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.759 seconds
[2025-07-26T09:41:20.195+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:41:20.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:41:20.199+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:41:20.199+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:41:22.076+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:41:22.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:41:22.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:41:22.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 1.948 seconds
[2025-07-26T09:41:52.590+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:41:52.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:41:52.605+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:41:52.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:41:53.162+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:41:53.146+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:41:53.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:41:53.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.648 seconds
[2025-07-26T09:42:23.676+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:42:23.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:42:23.683+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:42:23.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:42:24.163+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:42:24.144+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:42:24.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:42:24.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.551 seconds
[2025-07-26T09:42:54.688+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:42:54.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:42:54.693+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:42:54.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:42:55.239+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:42:55.227+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:42:55.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:42:55.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.610 seconds
[2025-07-26T09:43:25.778+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:43:25.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:43:25.785+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:43:25.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:43:26.409+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:43:26.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:43:26.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:43:26.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.697 seconds
[2025-07-26T09:43:56.876+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:43:56.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:43:56.883+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:43:56.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:43:57.563+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:43:57.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:43:57.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:43:57.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.749 seconds
[2025-07-26T09:44:27.883+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:44:27.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:44:27.887+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:44:27.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:44:28.444+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:44:28.425+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:44:28.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:44:28.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.620 seconds
[2025-07-26T09:44:59.046+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:44:59.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:44:59.051+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:44:59.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:44:59.930+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:44:59.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:44:59.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:45:00.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.970 seconds
[2025-07-26T09:45:30.539+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:45:30.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:45:30.546+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:45:30.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:45:31.146+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:45:31.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:45:31.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:45:31.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.714 seconds
[2025-07-26T09:46:01.675+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:46:01.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:46:01.679+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:46:01.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:46:02.261+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:46:02.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:46:02.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:46:02.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.637 seconds
[2025-07-26T09:46:32.760+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:46:32.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:46:32.765+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:46:32.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:46:33.368+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:46:33.350+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:46:33.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:46:33.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.699 seconds
[2025-07-26T09:47:03.740+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:47:03.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:47:03.745+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:47:03.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:47:04.356+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:47:04.338+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:47:04.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:47:04.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.666 seconds
[2025-07-26T09:47:34.789+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:47:34.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:47:34.798+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:47:34.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:47:35.375+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:47:35.359+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:47:35.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:47:35.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.671 seconds
[2025-07-26T09:48:05.998+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:48:06.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:48:06.009+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:48:06.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:48:06.591+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:48:06.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:48:06.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:48:06.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.656 seconds
[2025-07-26T09:48:37.139+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:48:37.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:48:37.148+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:48:37.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:48:37.794+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:48:37.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:48:37.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:48:37.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.711 seconds
[2025-07-26T09:49:08.308+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:49:08.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:49:08.317+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:49:08.316+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:49:08.837+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:49:08.823+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:49:08.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:49:08.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.587 seconds
[2025-07-26T09:49:39.331+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:49:39.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:49:39.339+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:49:39.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:49:39.793+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:49:39.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:49:39.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:49:39.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.520 seconds
[2025-07-26T09:50:10.267+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:50:10.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:50:10.271+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:50:10.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:50:10.713+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:50:10.698+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:50:10.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:50:10.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.484 seconds
[2025-07-26T09:50:41.063+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:50:41.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:50:41.068+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:50:41.067+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:50:41.560+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:50:41.546+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:50:41.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:50:41.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.543 seconds
[2025-07-26T09:51:12.098+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:51:12.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:51:12.108+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:51:12.106+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:51:12.609+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:51:12.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:51:12.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:51:12.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.563 seconds
[2025-07-26T09:51:43.085+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:51:43.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:51:43.097+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:51:43.096+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:51:43.649+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:51:43.633+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:51:43.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:51:43.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.617 seconds
[2025-07-26T09:52:14.194+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:52:14.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:52:14.206+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:52:14.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:52:14.812+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:52:14.796+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:52:14.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:52:14.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.676 seconds
[2025-07-26T09:52:45.324+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:52:45.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:52:45.328+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:52:45.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:52:45.793+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:52:45.777+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:52:45.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:52:45.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.509 seconds
[2025-07-26T09:53:16.265+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:53:16.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:53:16.275+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:53:16.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:53:16.745+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:53:16.729+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:53:16.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:53:16.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.553 seconds
[2025-07-26T09:53:47.312+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:53:47.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:53:47.316+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:53:47.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:53:47.752+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:53:47.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:53:47.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:53:47.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.499 seconds
[2025-07-26T09:54:18.086+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:54:18.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:54:18.097+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:54:18.096+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:54:18.799+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:54:18.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:54:18.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:54:18.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.774 seconds
[2025-07-26T09:54:49.356+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:54:49.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:54:49.367+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:54:49.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:54:49.915+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:54:49.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:54:49.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:54:49.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.630 seconds
[2025-07-26T09:55:20.493+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:55:20.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:55:20.501+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:55:20.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:55:20.988+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:55:20.970+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:55:20.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:55:21.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.570 seconds
[2025-07-26T09:55:51.465+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:55:51.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:55:51.471+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:55:51.471+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:55:51.991+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:55:51.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:55:51.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:55:52.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.576 seconds
[2025-07-26T09:56:22.534+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:56:22.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:56:22.544+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:56:22.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:56:23.099+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:56:23.081+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:56:23.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:56:23.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.654 seconds
[2025-07-26T09:56:53.357+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:56:53.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:56:53.367+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:56:53.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:56:53.942+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:56:53.928+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:56:53.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:56:53.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.637 seconds
[2025-07-26T09:57:24.506+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:57:24.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:57:24.516+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:57:24.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:57:25.099+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:57:25.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:57:25.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:57:25.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.677 seconds
[2025-07-26T09:57:55.478+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:57:55.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:57:55.485+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:57:55.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:57:55.930+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:57:55.917+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:57:55.933+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:57:55.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.506 seconds
[2025-07-26T09:58:26.481+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:58:26.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:58:26.488+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:58:26.487+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:58:26.951+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:58:26.933+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:58:26.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:58:27.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.676 seconds
[2025-07-26T09:58:57.520+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:58:57.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:58:57.527+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:58:57.526+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:58:58.142+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:58:58.129+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:58:58.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:58:58.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.826 seconds
[2025-07-26T09:59:28.893+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:59:28.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ml_pipeline_dag.py for tasks to queue
[2025-07-26T09:59:28.905+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:59:28.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:59:29.559+0000] {logging_mixin.py:188} INFO - [2025-07-26T09:59:29.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 9, in <module>
    from run_pipeline import main as run_pipeline
  File "/opt/airflow/src/run_pipeline.py", line 1, in <module>
    from data_preprocessing import preprocess_data
  File "/opt/airflow/src/data_preprocessing.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-07-26T09:59:29.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline_dag.py
[2025-07-26T09:59:29.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ml_pipeline_dag.py took 0.732 seconds
